[changelog]
header = "# Release Notes\n\n"
body = """
{% for group, commits in commits | group_by(attribute="group") %}
## {{ group | upper_first }}
{% for commit in commits %}
- {{ commit.message | split(pat="\n") | first }}
{% endfor %}
{% endfor %}
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_preprocessors = []
tag_pattern = "^v"
commit_parsers = [
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Fixes" },
  { message = "^docs", group = "Docs" },
  { message = "^refactor", group = "Refactors" },
  { message = "^perf", group = "Performance" },
  { message = "^test", group = "Tests" },
  { message = "^chore", group = "Chores" },
  { message = "^ci", group = "CI" },
]
